add_newline = false
palette = "catppuccin_mocha"
format = "$time$directory$git_branch$git_status$python$nodejs$golang$status$character"

[time]
disabled = true
time_format = "%H:%M"
style = "subtext"
format = "[$time]($style) "

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 3
format = "[$path]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "mauve"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "yellow"

[python]
symbol = " "
format = "[$symbol$version]($style) "
style = "green"

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "
style = "green"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "green"

[status]
disabled = false
symbol = "✘ "
format = "[$symbol$status]($style) "
style = "red"

[character]
success_symbol = "[# ](mauve)"
error_symbol = "[# ](mauve)"
vicmd_symbol = "[vi ](mauve)"

[palettes.catppuccin_mocha]
text = "#cdd6f4"
subtext = "#a6adc8"
blue = "#89b4fa"
mauve = "#cba6f7"
green = "#a6e3a1"
yellow = "#f9e2af"
red = "#f38ba8"
